# Module 1: VN100 Market Data Collection  
This notebook collects historical OHLCV data for the VN100 index constituents.  
- **Source:** Vietnamese stock market data.  
- **Objective:** Build a raw dataset in `.parquet` format to optimize processing performance for subsequent steps.

### 1.1 Library Imports and Project Root Configuration  
We set up the path to enable importing custom functions from the `src` directory.

In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
import seaborn as sn
import sys
import os
import matplotlib.pyplot as plt
import json
from datetime import date, timedelta

project_root = os.path.abspath("../../")

if project_root not in sys.path:
    sys.path.append(project_root)

import src.data_collect as dc

### 1.2 Data Collection Execution  
Use the `src.data_collect` module to retrieve the VN100 ticker list and download OHLCV data.

In [ ]:
VN100_tags = dc.build_vn100()

In [11]:
FILE_PATH = "../../data/market_data.parquet"
START_DATE = "2018-01-01"
BATCH_SIZE = 5  # save mỗi 5 mã

dc.update_market_data(
    FILE_PATH,
    VN100_tags,
    START_DATE,
    BATCH_SIZE
)

Resuming. Found data for 100 symbols.
Skip ACB (up to date)
Skip ANV (up to date)
Skip BCM (up to date)
Skip BID (up to date)
Skip BMP (up to date)
Skip BSI (up to date)
Skip BSR (up to date)
Skip BVH (up to date)
Skip BWE (up to date)
Skip CII (up to date)
Skip CMG (up to date)
Skip CTD (up to date)
Skip CTG (up to date)
Skip CTR (up to date)
Skip CTS (up to date)
Skip DBC (up to date)
Skip DCM (up to date)
Skip DGC (up to date)
Skip DGW (up to date)
Skip DIG (up to date)
Skip DPM (up to date)
Skip DSE (up to date)
Skip DXG (up to date)
Skip DXS (up to date)
Skip EIB (up to date)
Skip EVF (up to date)
Skip FPT (up to date)
Skip FRT (up to date)
Skip FTS (up to date)
Skip GAS (up to date)
Skip GEE (up to date)
Skip GEX (up to date)
Skip GMD (up to date)
Skip GVR (up to date)
Skip HAG (up to date)
Skip HCM (up to date)
Skip HDB (up to date)
Skip HDC (up to date)
Skip HDG (up to date)
Skip HHV (up to date)
Skip HPG (up to date)
Skip HSG (up to date)
Skip HT1 (up to date)
Skip IMP (up to date)
Skip KBC (up to date)
Skip KDC (up to date)
Skip KDH (up to date)
Skip KOS (up to date)
Skip LPB (up to date)
Skip MBB (up to date)
Skip MSB (up to date)
Skip MSN (up to date)
Skip MWG (up to date)
Skip NAB (up to date)
Skip NKG (up to date)
Skip NLG (up to date)
Skip NT2 (up to date)
Skip NVL (up to date)
Skip OCB (up to date)
Skip PAN (up to date)
Skip PC1 (up to date)
Skip PDR (up to date)
Skip PHR (up to date)
Skip PLX (up to date)
Skip PNJ (up to date)
Skip POW (up to date)
Skip PVD (up to date)
Skip PVT (up to date)
Skip REE (up to date)
Skip SAB (up to date)
Skip SBT (up to date)
Skip SCS (up to date)
Skip SHB (up to date)
Skip SIP (up to date)
Skip SJS (up to date)
Skip SSB (up to date)
Skip SSI (up to date)
Skip STB (up to date)
Skip SZC (up to date)
Skip TCB (up to date)
Skip TCH (up to date)
Skip TPB (up to date)
Skip VCB (up to date)
Skip VCG (up to date)
Skip VCI (up to date)
Skip VGC (up to date)
Skip VHC (up to date)
Skip VHM (up to date)
Skip VIB (up to date)
Skip VIC (up to date)
Skip VIX (up to date)
Skip VJC (up to date)
Skip VND (up to date)
Skip VNM (up to date)
Skip VPB (up to date)
Skip VPI (up to date)
Skip VPL (up to date)
Skip VRE (up to date)
Skip VSC (up to date)
Skip VTP (up to date)
🎯 Full dataset build completed.

In [ ]:
df = pd.read_parquet(FILE_PATH)
df.tail(5)

             date  open  high   low  close  volume Symbol
205147 2026-04-21  70.0  71.5  69.5   69.7  644100    VTP
205148 2026-04-22  68.5  69.7  66.9   67.7  842900    VTP
205149 2026-04-23  69.5  69.5  67.6   68.5  394800    VTP
205150 2026-04-24  68.7  71.0  68.6   69.4  390600    VTP
205151 2026-04-28  69.5  69.6  68.3   68.8  315200    VTP

# VNINDEX

In [13]:
FILE_PATH = "../../data/vnindex_data.parquet"
START_DATE = "2018-01-01"
dc.fetch_indicator_data(
    ind_symbol="VNINDEX", 
    start_date=START_DATE, 
    file_path=FILE_PATH
)

✓ Successfully saved VNINDEX data (2179 rows) to ../../data/vnindex_data.parquet

In [14]:
df = pd.read_parquet(FILE_PATH)
df.head()

        date    open    high     low   close     volume
0 2017-08-09  789.15  791.57  773.66  773.66  292795000
1 2017-08-10  769.58  776.77  769.58  773.43  178275390
2 2017-08-11  773.43  774.31  769.14  772.08  156752670
3 2017-08-14  772.17  776.42  772.01  776.17  159668260
4 2017-08-15  776.64  776.83  770.09  771.06  143870570