In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import sys
import os
import matplotlib.pyplot as plT
from datetime import date, timedelta

# 1. Get the absolute path of the folder two levels up (your main project folder)
project_root = os.path.abspath("../../")

# 2. Add that project folder to Python's search path
if project_root not in sys.path:
    sys.path.append(project_root)

# 3. NOW you can import using standard dot notation!
import src.data_collect as dc

# VN100

In [2]:


VN100_tags = dc.build_vn100()

VN30: 30
VNMID: 70
VN100: 100

Build Full

In [3]:
FILE_PATH = "../../data/market_data.parquet"
START_DATE = "2018-01-01"
BATCH_SIZE = 5  # save mỗi 5 mã

dc.update_market_data(
    FILE_PATH,
    VN100_tags,
    START_DATE,
    BATCH_SIZE
)

Resuming. Found data for 100 symbols.
Skip ACB (up to date)
Skip ANV (up to date)
Skip BCM (up to date)
Skip BID (up to date)
Skip BMP (up to date)
Skip BSI (up to date)
Skip BSR (up to date)
Skip BVH (up to date)
Skip BWE (up to date)
Skip CII (up to date)
Skip CMG (up to date)
Skip CTD (up to date)
Skip CTG (up to date)
Skip CTR (up to date)
Skip CTS (up to date)
Skip DBC (up to date)
Skip DCM (up to date)
Skip DGC (up to date)
Skip DGW (up to date)
Skip DIG (up to date)
Skip DPM (up to date)
Skip DSE (up to date)
Skip DXG (up to date)
Skip DXS (up to date)
Skip EIB (up to date)
Skip EVF (up to date)
Skip FPT (up to date)
Skip FRT (up to date)
Skip FTS (up to date)
Skip GAS (up to date)
Skip GEE (up to date)
Skip GEX (up to date)
Skip GMD (up to date)
Skip GVR (up to date)
Skip HAG (up to date)
Skip HCM (up to date)
Skip HDB (up to date)
Skip HDC (up to date)
Skip HDG (up to date)
Skip HHV (up to date)
Skip HPG (up to date)
Skip HSG (up to date)
Skip HT1 (up to date)
Skip IMP (up to date)
Skip KBC (up to date)
Skip KDC (up to date)
Skip KDH (up to date)
Skip KOS (up to date)
Skip LPB (up to date)
Skip MBB (up to date)
Skip MSB (up to date)
Skip MSN (up to date)
Skip MWG (up to date)
Skip NAB (up to date)
Skip NKG (up to date)
Skip NLG (up to date)
Skip NT2 (up to date)
Skip NVL (up to date)
Skip OCB (up to date)
Skip PAN (up to date)
Skip PC1 (up to date)
Skip PDR (up to date)
Skip PHR (up to date)
Skip PLX (up to date)
Skip PNJ (up to date)
Skip POW (up to date)
Skip PVD (up to date)
Skip PVT (up to date)
Skip REE (up to date)
Skip SAB (up to date)
Skip SBT (up to date)
Skip SCS (up to date)
Skip SHB (up to date)
Skip SIP (up to date)
Skip SJS (up to date)
Skip SSB (up to date)
Skip SSI (up to date)
Skip STB (up to date)
Skip SZC (up to date)
Skip TCB (up to date)
Skip TCH (up to date)
Skip TPB (up to date)
Skip VCB (up to date)
Skip VCG (up to date)
Skip VCI (up to date)
Skip VGC (up to date)
Skip VHC (up to date)
Skip VHM (up to date)
Skip VIB (up to date)
Skip VIC (up to date)
Skip VIX (up to date)
Skip VJC (up to date)
Skip VND (up to date)
Skip VNM (up to date)
Skip VPB (up to date)
Skip VPI (up to date)
Skip VPL (up to date)
Skip VRE (up to date)
Skip VSC (up to date)
Skip VTP (up to date)
🎯 Full dataset build completed.

In [4]:
df = pd.read_parquet(FILE_PATH)
df.head(5)

         date  open  high   low  close   volume Symbol
0  2017-08-08  4.63  4.65  4.55   4.56   382940    ACB
1  2017-08-09  4.56  4.56  4.46   4.49  1649412    ACB
2  2017-08-10  4.46  4.51  4.44   4.46  1139760    ACB
3  2017-08-11  4.48  4.48  4.44   4.46   774623    ACB
4  2017-08-14  4.44  4.51  4.44   4.51   657975    ACB

# VNINDEX

In [5]:
FILE_PATH = "../../data/vnindex_data.parquet"
START_DATE = "2018-01-01"
dc.fetch_indicator_data(
    ind_symbol="VNINDEX", 
    start_date=START_DATE, 
    file_path=FILE_PATH
)

✓ Successfully saved VNINDEX data (2167 rows) to ../../data/vnindex_data.parquet

In [6]:
df = pd.read_parquet(FILE_PATH)
df.head()

        date    open    high     low   close     volume
0 2017-08-15  776.64  776.83  770.09  771.06  143870570
1 2017-08-16  771.10  773.57  766.80  773.57  156131920
2 2017-08-17  773.48  774.47  766.80  767.59  220817310
3 2017-08-18  762.82  774.47  762.46  768.97  162337400
4 2017-08-21  767.42  774.47  762.46  768.79  152284410